obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.08, -0.15], [-0.08, 0.15],[0.22, 0.15],[0.22, -0.15]]
#robot_radius: ir_of_robot
inflation_radius: 0.1
transform_tolerance: 0.2

observation_sources: point_cloud_sensor

point_cloud_sensor: {sensor_frame: aft_mapped, data_type: PointCloud2, topic: /cloud_registered, marking: true, clearing: true}